# Generated by Django 3.2.16 on 2023-01-23 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_phone', models.CharField(max_length=20)),
                ('group_address', models.CharField(max_length=255)),
                ('group_id', models.CharField(default=portal.models.generate_unique_group_id, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sign', models.CharField(blank=True, max_length=2)),
                ('bio', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('class_studentnumber', models.IntegerField(blank=True)),
                ('class_course', models.CharField(max_length=255)),
                ('class_manager', models.CharField(max_length=255)),
                ('class_submanager', models.CharField(blank=True, max_length=255)),
                ('school_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.schoolgroup')),
            ],
        ),
    ]
