# Generated by Django 4.1.3 on 2023-01-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_groupinfomation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupinfomation",
            name="email",
        ),
        migrations.AddField(
            model_name="groupinfomation",
            name="bio",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="groupinfomation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="portal.schoolgroup"
            ),
        ),
    ]
