# Generated by Django 4.1.3 on 2023-01-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_remove_groupinfomation_email_groupinfomation_bio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupinfomation",
            old_name="user",
            new_name="school_group",
        ),
    ]
