# Generated by Django 4.1.3 on 2023-01-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_rename_user_groupinfomation_school_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolgroup",
            name="bio",
            field=models.TextField(default=""),
        ),
        migrations.DeleteModel(
            name="GroupInfomation",
        ),
    ]
