# Generated by Django 3.2.16 on 2022-12-15 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to=user_profile.models.upload_path)),
                ('date_of_birth', models.DateField(blank=True, help_text='The date of birth')),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('user_type', models.CharField(blank=True, choices=[('1', 'admin'), ('2', 'teacher'), ('3', 'student')], default='1', max_length=255)),
                ('teacher_library', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
