# Generated by Django 4.1.3 on 2022-11-21 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=255)),
                ("last_name", models.CharField(default="", max_length=255)),
                ("phone", models.CharField(default="", max_length=20)),
                ("address", models.CharField(default="", max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("1", "admin"), ("2", "teacher"), ("3", "student")],
                        default="1",
                        max_length=255,
                    ),
                ),
                ("only_read", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("school_library_manage", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("avatar", models.ImageField(upload_to="pictures")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
