# Generated by Django 4.1.3 on 2023-01-06 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "date_of_birth",
                    models.DateField(auto_now_add=True, help_text="The date of birth"),
                ),
                ("group_name", models.CharField(blank=True, max_length=255)),
                ("teacher_library", models.BooleanField(blank=True, default=False)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("1", "admin"), ("2", "teacher"), ("3", "student")],
                        default="1",
                        max_length=255,
                    ),
                ),
                (
                    "teacher_sex",
                    models.CharField(
                        choices=[("1", "male"), ("2", "female"), ("3", "others")],
                        default="1",
                        max_length=255,
                    ),
                ),
                ("teacher_belong_to_id", models.CharField(blank=True, max_length=255)),
                (
                    "teacher_belong_to_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("teacher_course", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to=user_profile.models.upload_path
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
