# Generated by Django 4.1.3 on 2023-01-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(help_text="The date of birth"),
        ),
    ]
