# Generated by Django 4.1.3 on 2022-11-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="can_edit",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="only_read",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="school_library_manage",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_type",
        ),
    ]
