# Generated by Django 4.1.3 on 2022-11-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_remove_userprofile_can_edit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user",
            new_name="email",
        ),
    ]
