# Generated by Django 4.1.3 on 2022-11-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_rename_user_userprofile_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="email",
            new_name="user",
        ),
    ]
