# Generated by Django 4.1.3 on 2023-01-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_alter_useravatar_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="group_name",
        ),
    ]
