# Generated by Django 4.1.3 on 2022-11-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="can_do_anything",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
