# Generated by Django 4.1.3 on 2022-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_useraccount_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
