# Generated by Django 4.1.3 on 2022-11-28 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_useraccount_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 11, 28, 5, 40, 4, 343953, tzinfo=datetime.timezone.utc
                ),
                max_length=45,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 11, 28, 5, 40, 11, 231856, tzinfo=datetime.timezone.utc
                ),
                max_length=45,
            ),
            preserve_default=False,
        ),
    ]
