# Generated by Django 4.1.3 on 2022-11-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_useraccount_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
