# Generated by Django 4.1.3 on 2022-11-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_useraccount_first_name_useraccount_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
