# Generated by Django 4.1.3 on 2022-11-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_useraccount_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraccount",
            options={},
        ),
        migrations.RenameField(
            model_name="useraccount",
            old_name="username",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="last_name",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="can_do_anything",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
