# Generated by Django 4.1.3 on 2022-11-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_useraccount_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="is_staff",
        ),
    ]
