# Generated by Django 4.1.3 on 2022-11-21 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_useraccount_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="can_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 11, 21, 6, 19, 59, 762865, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="only_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="school_library_manage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="user_type",
            field=models.CharField(
                choices=[("1", "admin"), ("2", "teacher"), ("3", "student")],
                default="1",
                max_length=255,
            ),
        ),
    ]
