# Generated by Django 4.1.3 on 2022-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_useraccount_can_edit_useraccount_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="user_type",
            field=models.CharField(
                choices=[("1", "admin"), ("2", "teacher"), ("3", "student")],
                max_length=255,
            ),
        ),
    ]
