# Generated by Django 4.1.3 on 2022-11-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_useraccount_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="user_type",
            field=models.CharField(
                choices=[("1", "admin"), ("2", "teacher"), ("3", "student")],
                default="1",
                max_length=255,
            ),
        ),
    ]
