# Generated by Django 4.1.3 on 2022-11-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_useraccount_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
