# Generated by Django 4.1.3 on 2022-11-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_useraccount_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
